[package]
name = "tiles"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
physics = { path = "../physics" }
network = { path = "../network" }
wincode = { version = "0.4", features = ["derive"] }
