[package]
name = "items"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
things = { path = "../things" }
physics = { path = "../physics" }
network = { path = "../network" }
