[package]
name = "atmospherics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
tiles = { path = "../tiles" }
network = { path = "../network" }
wincode = { workspace = true }
