[package]
name = "things"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
physics = { path = "../physics" }
network = { path = "../network" }
serde = { workspace = true }
wincode = { workspace = true }
